// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	orders "shiva/shiva-auth/internal/orders"

	mock "github.com/stretchr/testify/mock"
)

// MockupIoRepository is an autogenerated mock type for the MockupIoRepository type
type MockupIoRepository struct {
	mock.Mock
}

// GetMockListrik provides a mock function with given fields: id
func (_m *MockupIoRepository) GetMockListrik(id string) (orders.Domain, error) {
	ret := _m.Called(id)

	var r0 orders.Domain
	if rf, ok := ret.Get(0).(func(string) orders.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(orders.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMockPDAM provides a mock function with given fields: id
func (_m *MockupIoRepository) GetMockPDAM(id string) (orders.Domain, error) {
	ret := _m.Called(id)

	var r0 orders.Domain
	if rf, ok := ret.Get(0).(func(string) orders.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(orders.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
