// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	orders "shiva/shiva-auth/internal/orders"

	mock "github.com/stretchr/testify/mock"
)

// XenditRepository is an autogenerated mock type for the XenditRepository type
type XenditRepository struct {
	mock.Mock
}

// CreateVA provides a mock function with given fields: id, bankCode
func (_m *XenditRepository) CreateVA(id string, bankCode string) (orders.Domain, error) {
	ret := _m.Called(id, bankCode)

	var r0 orders.Domain
	if rf, ok := ret.Get(0).(func(string, string) orders.Domain); ok {
		r0 = rf(id, bankCode)
	} else {
		r0 = ret.Get(0).(orders.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, bankCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentChannels provides a mock function with given fields:
func (_m *XenditRepository) PaymentChannels() ([]orders.Domain, error) {
	ret := _m.Called()

	var r0 []orders.Domain
	if rf, ok := ret.Get(0).(func() []orders.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]orders.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
